PandaReach-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0

PandaPush-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0

PandaSlide-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0

  
PandaPickAndPlace-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0



PandaReachDense-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0

PandaPushDense-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0

PandaSlideDense-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0

"""  
PandaPickAndPlaceDense-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0

"""


PandaReachJoints-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0





PandaReachJointsDense-v3:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.0




#Hyperparametertuning

PandaPickAndPlaceDense-v3:
  normalize: true
  learning_rate: 0.00066
  policy: 'MultiInputPolicy'
  n_steps: 16
  batch_size: 2048
  gae_lambda: 0.9
  gamma: 0.9
  n_epochs: 10
  ent_coef: 0.00286
  activation_fn: 'relu'
  net_arch: "medium"

