



PandaReachDense-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"

PandaPushDense-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"

PandaSlideDense-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"
"""
PandaPickAndPlaceDense-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"

"""
PandaReach-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"

PandaPush-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"

PandaSlide-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"

PandaPickAndPlace-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"



PandaReachJointsDense-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"

PandaReachJoints-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[64, 64])"




#Hyperparametertuning

PandaPickAndPlaceDense-v3:
  n_timesteps: !!float 1000000.0
  policy: 'MultiInputPolicy'
  buffer_size: 100000
  batch_size: 1024
  learning_rate: 0.00071
  normalize: true
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict( goal_selection_strategy='future', n_sampled_goal=4, )"
  policy_kwargs: "dict(net_arch=[256, 256, 256])"
  tau: 0.0005
  gamma: 0.995
  train_freq: 64
  learning_starts: 1000
